# Generated by Django 6.0 on 2025-12-05 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_photos',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_photos',
            field=models.BinaryField(),
        ),
        migrations.CreateModel(
            name='HotelPhoto',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.room')),
            ],
        ),
    ]
