# Generated by Django 6.0 on 2025-12-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_alter_hotel_hotel_photos_alter_room_room_photos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelphoto',
            name='value',
        ),
        migrations.RemoveField(
            model_name='roomphoto',
            name='value',
        ),
        migrations.AddField(
            model_name='hotelphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_photos'),
        ),
        migrations.AddField(
            model_name='roomphoto',
            name='room_photo',
            field=models.ImageField(blank=True, null=True, upload_to='room_photos'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_photos',
            field=models.ImageField(upload_to='hotel_photos'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_photos',
            field=models.ImageField(upload_to='room_photos'),
        ),
    ]
