# Generated by Django 6.0 on 2025-12-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_remove_hotelphoto_value_remove_roomphoto_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
