# Generated by Django 6.0 on 2025-12-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_hotel_hotel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='available',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
