# Generated by Django 6.0 on 2025-12-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0006_remove_hotel_hotel_photos_remove_room_room_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available',
            field=models.BooleanField(),
        ),
    ]
