# Generated by Django 6.0 on 2025-12-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0007_alter_room_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(blank=True, default='standart', max_length=100),
        ),
    ]
