# Generated by Django 6.0 on 2025-12-11 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0008_room_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='chck_out',
            new_name='check_out',
        ),
    ]
